server_ip: "34.136.74.155"
embeddings_server_ip: "35.223.126.222"
embeddings_domain: "llm.pangolin.live"
server_user: "kegor"
server_key: "~/.ssh/id_ed25519"
deploy_dir: "/opt/pangolin"
ghcr_owner: "securitsa"
dialogue_tag: "latest"
identity_tag: "latest"
pulse_tag: "latest"
app_port: 8000
semantic_hub_tag: "latest"
prediction_hub_tag: "latest"
gcs_project_id: "vmesto-staging"
