all:
  hosts:
    pangolin-server:
      ansible_host: "{{ server_ip }}"
      ansible_user: "{{ server_user }}"
      ansible_ssh_private_key_file: "{{ server_key }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    server_ip: "104.154.203.237"
    server_user: "kegor"
